Cleanup flavor template config every time before update template, check status of template via vzpkg not rpm utility

diff --git a/update-cache b/update-cache
--- a/update-cache
+++ b/update-cache
@@ -23,7 +23,7 @@ prepare() {
 	FLAVOR=$(echo $1 | sed -e 's/^.*-\(minimal\|devel\)$/\1/g')
 	NAME=$(echo $t | sed 's/^\(.*\)-\(minimal\|devel\)$/\1/g')
 	CONFPATH=`$VZPKG info $NAME config_path | grep template | sed 's/^[ \t]*\(.*\)default$/\1/g'`
-	if [ -e $CONFPATH/$FLAVOR ]; then return 0; fi
+	if [ -e $CONFPATH/$FLAVOR ]; then rm -rf $CONFPATH/$FLAVOR; fi
 	mkdir $CONFPATH/$FLAVOR
 	cd $CONFPATH/$FLAVOR
 	ls -1 ../default/ | while read i; do ln -s ../default/$i $i; done
@@ -41,17 +41,18 @@ install() {
 		if isflavor $t; then
 			name=$(echo $t | sed 's/^\(.*\)-\(devel\|minimal\)$/\1/g')
 			log "[$i/$#] Full template name is $t, base template is $name"
-			if ! rpm -q --quiet "$name"-ez; then
-				$YUM install -y $name"-ez" || ( log "[$i/$#] Failed to install $name"; exit 1 )
+			if ! vzpkg status $name; then
+				$YUM install -y $name || ( log "[$i/$#] Failed to install $name"; exit 1 )
 			else
-				$YUM update -y $name"-ez" || ( log "[$i/$#] Failed to update $name"; exit 1 )
+				$YUM update -y $name || ( log "[$i/$#] Failed to update $name"; )
 			fi
+			log "[$i/$#] Preparing flavor template $name";
 			prepare $t
 		else
-			if ! rpm -q --quiet $t"-ez"; then
-				$YUM install -y $t"-ez" || ( log "[$i/$#] Failed to install $t"; exit 1 )
+			if ! vzpkg status $t; then
+				$YUM install -y $t || ( log "[$i/$#] Failed to install $t"; exit 1 )
 			else
-				$YUM update -y $t"-ez" || ( log "[$i/$#] Failed to update $t"; exit 1 )
+				$YUM update -y $t || ( log "[$i/$#] Failed to update $t"; )
 			fi
 		fi
 		let i++
